modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="nebs" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Neko’s Enchanted Books" #mandatory
authors="Nekomaster, CGessinger" #optional
description=''' '''

[[dependencies.nebs]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="CLIENT"

[[dependencies.nebs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"
